fix: Update .tmux.conf
ERROR: tmux save-buffer - | xclip -i -sel clipboard > /dev/null
Can not save select text into clipboard, because of no display